apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  replicas: 1
  serviceName: database
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql
          args:
            - '--default-authentication-plugin=mysql_native_password'
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /opt/database-credentials/password
            - name: MYSQL_DATABASE
              value: database
          volumeMounts:
            - name: credentials
              mountPath: /opt/database-credentials
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: credentials
          secret:
            secretName: database-credentials

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 1Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
